lora_monitor/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_view, name='register'),
]

lora_monitor/devices/urls.py
from django.urls import path
from . import views
from .api import TTNWebhookView

app_name = 'devices'

urlpatterns = [
    path('', views.device_list, name='list'),
    path('<int:pk>/', views.device_detail, name='detail'),
    path('create/', views.device_create, name='create'),
    path('<int:pk>/update/', views.device_update, name='update'),
    path('<int:pk>/delete/', views.device_delete, name='delete'),
    path("api/ttn/webhook/", TTNWebhookView.as_view(), name="ttn_webhook"),
]

lora_monitor/lora_monitor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('devices.urls', namespace='devices')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

lora_monitor/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <span class="logo">Lora Monitor</span>
        {% if request.user.is_authenticated %}
        <ul class="menu">
             <li>
                <a href="{% url 'devices:list' %}">Panel główny</a>
             </li>
         </ul>
         {% endif %}
         <span class="user">
         {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}">Wyloguj</a>
         {% else %}
            <a href="{% url 'accounts:login' %}">Zaloguj</a>
            <a href="{% url 'accounts:register' %}">Zarejestruj</a>
         {% endif %}</span>
    </div>
    <div id="content">
    {% block content %}

    {% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet.heat/dist/leaflet-heat.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        $(document).ready(function() {
            {% block domready %}
            {% endblock %}
        });
    </script>
</body>
</html>